layout:
    actions:
        - '@setBlockTheme':
            themes: 'require_js_config.html.twig'
        - '@add':
            id: require_js_config
            parentId: require_js
            blockType: block

        - '@add':
            id: require_js_multi_select_filter_config
            parentId: require_js
            blockType: block

        - '@setOption':
            id: require_js_multi_select_filter_config
            optionName: visible
            optionValue: '=data["system_config_provider"].getValue("oro_frontend.filter_value_selectors")=="all_at_once"'
