layout:
    actions:
        - '@setBlockTheme':
            themes: 'js_components_config.html.twig'

        - '@setOption':
            id: page_title
            optionName: defaultValue
            optionValue: 'oro_frontend_style_book.groups.grid.title'
