api:
    entity_aliases:
        Extend\Entity\EV_Acc_Internal_Rating:
           alias:        customer_rating
           plural_alias: customer_rating
        Oro\Bundle\CustomerBundle\Entity\CustomerGroup:
           alias:        customer_group
           plural_alias: customer_groups
        Oro\Bundle\CustomerBundle\Entity\CustomerUserRole:
           alias:        customer_user_role
           plural_alias: customer_user_roles
        Oro\Bundle\CustomerBundle\Entity\CustomerUser:
           alias:        customer_user
           plural_alias: customer_users
    entities:
        Oro\Bundle\CustomerBundle\Entity\Customer:
            documentation_resource: '@OroCustomerBundle/Resources/doc/api/customer_entity.md'
        Oro\Bundle\CustomerBundle\Entity\CustomerGroup: ~
        Oro\Bundle\CustomerBundle\Entity\CustomerUserRole: ~
        Oro\Bundle\CustomerBundle\Entity\CustomerUser:
            documentation_resource: '@OroCustomerBundle/Resources/doc/api/customer_user_entity.md'
            fields:
                salt:
                    exclude: true
                password:
                    exclude: true
                plainPassword:
                    exclude: true
                confirmationToken:
                    exclude: true
            actions:
                create:
                    fields:
                        createdAt:
                            exclude: true
                        updatedAt:
                            exclude: true
                        passwordChangedAt:
                            exclude: true
                        passwordRequestedAt:
                            exclude: true
                        loginCount:
                            exclude: true
                        lastLogin:
                            exclude: true
                        password:
                            exclude: false # set manually because this field is excluded globally
                            form_options:
                                property_path: plainPassword
                                constraints:
                                    - NotNull: ~
                                    - NotBlank: ~
                update:
                    fields:
                        createdAt:
                            exclude: true
                        updatedAt:
                            exclude: true
                        passwordChangedAt:
                            exclude: true
                        passwordRequestedAt:
                            exclude: true
                        loginCount:
                            exclude: true
                        lastLogin:
                            exclude: true
