features:
    oro_customer_confirmation_required:
        label: oro.customer.system_configuration.fields.oro_customer_confirmation_required.label
        description: oro.customer.system_configuration.fields.oro_customer_confirmation_required.description
        toggle: oro_customer.confirmation_required
