system_configuration:
    groups:
        customer:
            title: oro.customer.system_configuration.groups.customer.title
        customer_users:
            title: oro.customer.system_configuration.groups.customer_users.title
            icon: 'fa-user'
        customer_users_registration:
            title: oro.customer.system_configuration.groups.customer_users_registration.title
            icon: 'fa-user-plus'
        menu_templates:
            title: oro.customer.system_configuration.groups.menu_templates.title
        customer_visitor_section:
            title: oro.customer.system_configuration.groups.customer_visitor_section.title
    fields:
        oro_customer.default_customer_owner:
            ui_only: true
            data_type: string
            type: oro_user_select
            priority: 110
            options:
                label: oro.customer.system_configuration.fields.default_customer_owner.label
                tooltip: oro.customer.system_configuration.fields.default_customer_owner.tooltip
                required: true
                configs:
                    allowClear: false
                    placeholder: 'oro.user.form.choose_user'
                    result_template_twig: 'OroUserBundle:User:Autocomplete/result.html.twig'
                    selection_template_twig: 'OroUserBundle:User:Autocomplete/selection.html.twig'
                constraints:
                    - NotBlank: ~
        oro_customer.registration_allowed:
            data_type: boolean
            type: oro_config_checkbox
            priority: 100
            options:
                label: oro.customer.system_configuration.fields.registration_allowed.label
                tooltip: oro.customer.system_configuration.fields.registration_allowed.tooltip
                required: false
        oro_customer.confirmation_required:
            data_type: boolean
            type: oro_config_checkbox
            priority: 90
            options:
                label: oro.customer.system_configuration.fields.confirmation_required.label
                tooltip: oro.customer.system_configuration.fields.confirmation_required.tooltip
                required: false
        oro_customer.send_password_in_welcome_email:
            data_type: boolean
            type: oro_config_checkbox
            priority: 80
            options:
                label: oro.customer.system_configuration.fields.send_password_in_welcome_email.label
                tooltip: oro.customer.system_configuration.fields.send_password_in_welcome_email.tooltip
                required: false
        oro_customer.registration_instructions_enabled:
            data_type: boolean
            type: oro_config_checkbox
            priority: 70
            options:
                label: oro.customer.system_configuration.fields.registration_instructions_enabled.label
                tooltip: oro.customer.system_configuration.fields.registration_instructions_enabled.tooltip
                required: false
        oro_customer.registration_instructions_text:
            data_type: string
            type: textarea
            priority: 60
            options:
                label: oro.customer.system_configuration.fields.registration_instructions_text.label
                required: false
        oro_customer.user_menu_show_items:
            data_type: string
            type: choice
            priority: 50
            options:
                label: oro.customer.system_configuration.fields.user_menu_show_items.label
                required: true
                choices:
                    all_at_once: oro.customer.system_configuration.fields.user_menu_show_items.option.all_at_once.label
                    subitems_in_popup: oro.customer.system_configuration.fields.user_menu_show_items.option.subitems_in_popup.label
        oro_customer.customer_visitor_cookie_lifetime_days:
            data_type: integer
            type: integer
            options:
                required: false
                label: oro.customer.system_configuration.fields.customer_visitor_cookie_lifetime_days.label
                tooltip: oro.customer.system_configuration.fields.customer_visitor_cookie_lifetime_days.tooltip
                constraints:
                    - NotBlank: ~
                    - Range:
                        min: 1
    tree:
        system_configuration:
            commerce:
                children:
                    customer:
                        priority: 1000
                        children:
                            customer_users:
                                priority: 100
                                children:
                                    customer_users_registration:
                                        children:
                                            - oro_customer.default_customer_owner
                                            - oro_customer.registration_allowed
                                            - oro_customer.confirmation_required
                                            - oro_customer.send_password_in_welcome_email
                                            - oro_customer.registration_instructions_enabled
                                            - oro_customer.registration_instructions_text
                                    customer_visitor_section:
                                        children:
                                            - oro_customer.customer_visitor_cookie_lifetime_days

                    design:
                        children:
                            theme:
                                children:
                                    menu_templates:
                                        children:
                                            - oro_customer.user_menu_show_items
