styles:
    inputs:
        - 'bundles/orofrontend/custom/scss/variables/page-main-config.scss'
        - 'bundles/orofrontend/custom/scss/variables/breadcrumbs-config.scss'
        - 'bundles/orofrontend/custom/scss/styles.scss'
    output: 'css/layout/custom/styles.css'
