layout:
    actions:
        - '@setBlockTheme':
            themes: 'OroFrontendBundle:layouts:default/oro_frontend_style_book_group/components_config.html.twig'

    conditions: 'context["group"]=="configs"'
