styles:
    inputs:
        - 'bundles/orofrontend/default/vendors/slick/slick.css'
        - 'bundles/orofrontend/blank/scss/variables/bootstrap4-variables-config.scss' # Must be first from *.scss
        - 'bundles/orofrontend/blank/scss/variables/btn-group-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/bootstrap4-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/breadcrumbs-config.scss'
        - 'bundles/orofrontend/blank/scss/settings/global-settings.scss'
        - 'bundles/orofrontend/blank/scss/variables/notification-flash-container-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/table-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/ui/dialog-config.scss'
        - 'bundles/orofrontend/blank/scss/styles.scss'

stylebook_styles:
    inputs:
        - 'bundles/bowerassets/prism/themes/prism-coy.css'
        - 'bundles/orofrontend/blank/scss/variables/style-book/style-book-sticky-elements-nav-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/style-book/style-book-title-config.scss'
        - 'bundles/orofrontend/blank/scss/style-book.scss'
    filters: ['cssrewrite', 'cssmin']
    output: 'css/layout/blank/stylebook.css'
