config:
    shim:
        'slick':
            deps:
                - 'jquery'
    map:
        '*':
            'oroui/templates/modal-dialog.html': 'orofrontend/default/templates/ui/modal-dialog.html'
            'oroui/templates/standart-confirmation.html': 'orofrontend/default/templates/ui/modal-dialog.html'
            'oroui/templates/delete-confirmation.html': 'orofrontend/default/templates/ui/modal-dialog.html'
            'oroui/templates/message-item.html': 'orofrontend/default/templates/ui/message-item.html'
            'orodatagrid/templates/column-manager/column-manager-collection.html': 'orofrontend/default/templates/datagrid/column-manager-collection.html'
            'orodatagrid/templates/column-manager/column-manager-item.html': 'orofrontend/default/templates/datagrid/column-manager-item.html'
            'orodatagrid/templates/column-manager/column-manager-filter.html': 'orofrontend/default/templates/datagrid/column-manager-filter.html'
            'orodatagrid/templates/column-manager/column-manager.html': 'orofrontend/default/templates/datagrid/column-manager.html'
            'orodatagrid/templates/datagrid/pagination-input.html': 'orofrontend/default/templates/datagrid/pagination-input.html'
            'orodatagrid/templates/datagrid/page-size.html': 'orofrontend/default/templates/datagrid/page-size.html'
            'orodatagrid/templates/datagrid/visible-items-counter.html': 'orofrontend/default/templates/datagrid/visible-items-counter.html'
            'orodatagrid/templates/datagrid/select-all-header-cell.html': 'orofrontend/default/templates/datagrid/select-all-header-cell.html'
            'orodatagrid/templates/datagrid/select-row-cell.html': 'orofrontend/default/templates/datagrid/select-row-cell.html'
            'orodatagrid/templates/datagrid/action-header-cell.html': 'orofrontend/default/templates/datagrid/action-header-cell.html'
            'orodatagrid/templates/datagrid/grid-view-label.html': 'orofrontend/default/templates/datagrid/grid-view-label.html'
            # Filters templates
            'orofilter/templates/filters-container.html': 'orofrontend/templates/filters/filters-container.html'
            'orofilter/templates/filter/filter-hint.html': 'orofrontend/templates/filters/filter-hint.html'
            'orofilter/templates/filter/filter-wrapper.html': 'orofrontend/templates/filters/filter-wrapper.html'
            'orofilter/templates/filter/choice-filter.html': 'orofrontend/templates/filters/choice-filter.html'
            'orofilter/templates/filter/number-range-filter.html': 'orofrontend/templates/filters/number-range-filter.html'
            'orofilter/templates/filter/many-to-many-filter.html': 'orofrontend/templates/filters/many-to-many-filter.html'
            'orofilter/templates/filter/dictionary-filter.html': 'orofrontend/templates/filters/dictionary-filter.html'
            'orofilter/templates/filter/select-filter.html': 'orofrontend/templates/filters/select-filter.html'
            'orofilter/templates/filter/embedded/simple-choice-filter.html': 'orofrontend/templates/filters/embedded/simple-choice-filter.html'
            'orofilter/templates/filter/choice-tree.html': 'orofrontend/templates/filters/choice-tree.html'
            'orofilter/templates/filter/date-filter.html': 'orofrontend/templates/filters/date-filter.html'
            'orofilter/templates/filter/date-filter-dropdown.html': 'orofrontend/templates/filters/date-filter-dropdown.html'
            'orofilter/templates/filter/date-picker.html': 'orofrontend/templates/filters/date-picker.html'
            'orofilter/templates/filter/multiselect-filter.html': 'orofrontend/templates/filters/multiselect-filter.html'
            'orofilter/templates/filter/none-filter.html': 'orofrontend/templates/filters/none-filter.html'
            'orofilter/templates/filter/select-field.html': 'orofrontend/templates/filters/select-field.html'
            'orofilter/templates/filter/text-filter.html': 'orofrontend/templates/filters/text-filter.html'
            # Filters templates END
            'orofilter/js/plugins/filters-toggle-plugin': 'orofrontend/js/app/datafilter/plugins/frontend-filters-plugin'
        'orofrontend/js/app/datafilter/plugins/frontend-filters-plugin':
            'orofilter/js/plugins/filters-toggle-plugin': 'orofilter/js/plugins/filters-toggle-plugin'
    paths:
        'orofrontend/js/app/components/widget-form-component': 'bundles/orofrontend/js/app/components/widget-form-component.js'
        'orofrontend/js/app/components/switchable-editable-view-component': 'bundles/orofrontend/js/app/components/switchable-editable-view-component.js'
        'orofrontend/js/app/components/attached-editable-view-component': 'bundles/orofrontend/js/app/components/attached-editable-view-component.js'
        'orofrontend/js/app/views/theme-select-view': 'bundles/orofrontend/js/app/views/theme-select-view.js'

        'orofrontend/js/app/views/viewer/title-view': 'bundles/orofrontend/js/app/views/viewer/title-view.js'
        'orofrontend/js/app/views/viewer/text-view': 'bundles/orofrontend/js/app/views/viewer/text-view.js'

        'orofrontend/js/app/views/editor/title-editor-view': 'bundles/orofrontend/js/app/views/editor/title-editor-view.js'
        'orofrontend/js/app/views/editor/multiline-text-editor-view': 'bundles/orofrontend/js/app/views/editor/multiline-text-editor-view.js'
        'orofrontend/js/app/views/scrollable-table': 'bundles/orofrontend/js/app/views/scrollable-table.js'

        'orofrontend/js/app/views/inline-editable-wrapper-view': 'bundles/orofrontend/js/app/views/inline-editable-wrapper-view.js'
        'orofrontend/js/app/modules/inline-editor-types-map-module': 'bundles/orofrontend/js/app//modules/inline-editor-types-map-module.js'
        'orofrontend/js/app/components/delete-item-component': 'bundles/orofrontend/js/app/components/delete-item-component.js'
        'orofrontend/js/app/components/empty-items-component': 'bundles/orofrontend/js/app/components/empty-items-component.js'
        'orofrontend/default/js/widgets/expand-text-widget': 'bundles/orofrontend/default/js/widgets/expand-text-widget.js'
        'orofrontend/default/js/widgets/line-clamp-widget': 'bundles/orofrontend/default/js/widgets/line-clamp-widget.js'
        'orofrontend/default/js/widgets/rows-collapse-widget': 'bundles/orofrontend/default/js/widgets/rows-collapse-widget.js'
        'orofrontend/default/js/widgets/elastic-area-widget': 'bundles/orofrontend/default/js/widgets/elastic-area-widget.js'
        'orofrontend/default/js/app/views/footer-align-view': 'orofrontend/default/js/app/views/footer-align-view.js'
        'orofrontend/default/js/app/views/sticky-panel-view': 'orofrontend/default/js/app/views/sticky-panel-view.js'
        'orofrontend/default/js/app/views/scroll-top-view': 'bundles/orofrontend/default/js/app/views/scroll-top-view.js'
        'orofrontend/blank/js/app/views/fullscreen-popup-view': 'orofrontend/blank/js/app/views/fullscreen-popup-view.js'
        'orofrontend/js/app/views/dom-relocation-view': 'orofrontend/js/app/views/dom-relocation-view.js'
        'orofrontend/js/app/views/style-book-elements-navigation-view': 'orofrontend/js/app/views/style-book-elements-navigation-view.js'
        'orofrontend/default/js/app/modules/input-widgets': 'bundles/orofrontend/default/js/app/modules/input-widgets.js'
        'orofrontend/default/js/app/modules/zoom-disable': 'bundles/orofrontend/default/js/app/modules/zoom-disable.js'
        'orofrontend/default/js/app/modules/choice-filter': 'bundles/orofrontend/default/js/app/modules/choice-filter.js'
        'orofrontend/default/js/app/modules/select-filter': 'bundles/orofrontend/default/js/app/modules/select-filter.js'
        'orofrontend/js/app/elements-helper': 'bundles/orofrontend/js/app/elements-helper.js'
        'orofrontend/js/app/datafilter/frontend-collection-filters-manager': 'bundles/orofrontend/js/app/datafilter/frontend-collection-filters-manager.js'
        'orofrontend/js/app/datafilter/frontend-multiselect-decorator': 'bundles/orofrontend/js/app/datafilter/frontend-multiselect-decorator.js'
        'orofrontend/js/app/datafilter/fronend-manage-filters-decorator': 'bundles/orofrontend/js/app/datafilter/fronend-manage-filters-decorator.js'
        'orofrontend/js/app/datafilter/plugins/frontend-filters-plugin': 'orofrontend/js/app/datafilter/plugins/frontend-filters-plugin.js'
        'orofrontend/js/app/datafilter/actions/fullscreen-filters-action': 'orofrontend/js/app/datafilter/actions/fullscreen-filters-action.js'

        'slick': 'bundles/orofrontend/default/vendors/slick/slick.js'
        'orofrontend/js/app/components/list-slider-component': 'bundles/orofrontend/js/app/components/list-slider-component.js'
        'orofrontend/js/app/components/popup-gallery-widget': 'bundles/orofrontend/js/app/components/popup-gallery-widget.js'
        'orofrontend/js/app/components/column-manager/frontend-column-manager-component': 'bundles/orofrontend/js/app/components/column-manager/frontend-column-manager-component.js'
        'orofrontend/js/app/views/column-manager/frontend-column-manager-view': 'bundles/orofrontend/js/app/views/column-manager/frontend-column-manager-view.js'
        'orofrontend/js/datagrid/grid-views/frontend-grid-views-view': 'bundles/orofrontend/js/datagrid/grid-views/frontend-grid-views-view.js'
        'orofrontend/js/app/views/object-fit-polyfill-view': 'orofrontend/js/app/views/object-fit-polyfill-view.js'

        'orofrontend/js/app/modules/component-shortcuts-module': 'bundles/orofrontend/js/app/modules/component-shortcuts-module.js'
    appmodules:
        - orofrontend/js/app/modules/inline-editor-types-map-module
        - orofrontend/js/app/modules/component-shortcuts-module
