services:
    # Data converter
    oro_customer.importexport.data_converter.customer:
        parent: oro_importexport.data_converter.configurable
        class: Oro\Bundle\CustomerBundle\ImportExport\Converter\CustomerDataConverter

    # Customer Export
    oro_customer.importexport.processor.export.customer:
        public: false
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, ['@oro_customer.importexport.data_converter.customer']]
        tags:
            - { name: oro_importexport.processor, type: export, entity: '%oro_customer.entity.customer.class%', alias: oro_customer_customer }

    # Customer Import
    oro_customer.importexport.strategy.customer.add_or_replace:
        class: Oro\Bundle\CustomerBundle\ImportExport\Strategy\CustomerAddOrReplaceStrategy
        parent: oro_importexport.strategy.configurable_add_or_replace

    oro_customer.importexport.processor.import:
        parent: oro_importexport.processor.import_abstract
        calls:
            - [setDataConverter, ['@oro_customer.importexport.data_converter.customer']]
            - [setStrategy, ['@oro_customer.importexport.strategy.customer.add_or_replace']]
        tags:
            - name: oro_importexport.processor
              type: import
              entity: '%oro_customer.entity.customer.class%'
              alias: oro_customer_customer

    # Customer Data Normalizer
    oro_customer.importexport.serializer.normalizer.customer:
        class: Oro\Bundle\CustomerBundle\ImportExport\Serializer\Normalizer\CustomerNormalizer
        parent: oro_importexport.serializer.configurable_entity_normalizer
        tags:
            - { name: oro_importexport.normalizer }

    # Customer User Data Converter
    oro_customer.importexport.data_converter.customer_user:
        parent: oro_importexport.data_converter.configurable

    # Customer User Export
    oro_customer.importexport.processor.export.customer_user:
        public: false
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, ['@oro_customer.importexport.data_converter.customer_user']]
        tags:
            - name: oro_importexport.processor
              type: export
              entity: '%oro_customer.entity.customer_user.class%'
              alias: oro_customer_customer_user

    # Customer Fixtures
    oro_customer.importexport.template_fixture.customer:
        public: false
        class: Oro\Bundle\CustomerBundle\ImportExport\TemplateFixture\CustomerFixture
        arguments:
            - '@oro_entity_extend.enum_value_provider'
        tags:
            - { name: oro_importexport.template_fixture }

    oro_customer.importexport.processor.export_template:
        public: false
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, [@oro_customer.importexport.data_converter.customer]]
        tags:
            - { name: oro_importexport.processor, type: export_template, entity: '%oro_customer.entity.customer.class%', alias: oro_customer_customer }
