api:
    entities:
        Oro\Bundle\WebsiteBundle\Entity\Website:
            actions:
                get: false
                create: false
                update: false
                delete: false
                delete_list: false
