Oro\Bundle\CommerceMenuBundle\Entity\MenuUpdate:
    constraints:
        - Oro\Bundle\NavigationBundle\Validator\Constraints\MaxNestedLevel: ~
    properties:
        titles:
            - Valid: ~
        uri:
            - NotBlank:
                groups: [UserDefined]

Oro\Bundle\CommerceMenuBundle\Entity\MenuUserAgentCondition:
    properties:
        value:
            - NotBlank: ~
            - Length:
                max: 255
