system_configuration:
    groups:
        design:
            title: oro_frontend.system_configuration.groups.design.title
        theme:
            title: oro_frontend.system_configuration.groups.theme.title
            icon: 'fa-picture-o'
        theme_settings:
            title: oro_frontend.system_configuration.groups.theme_settings.title
        commerce:
            title: oro_frontend.system_configuration.groups.commerce.title
            icon:  fa-shopping-cart
        page_templates:
            title: oro_frontend.system_configuration.groups.page_templates.title

    fields:
        oro_frontend.frontend_theme:
            data_type: string
            type: oro_frontend_theme_select
            priority: 100
            options:
                label: oro_frontend.system_configuration.fields.frontend_theme.label

        oro_frontend.page_templates:
            data_type: array
            type: oro_frontend_page_template_collection
            priority: 90
            options:
                required: false
                label: oro_frontend.system_configuration.fields.page_template_routes.label
                resettable: false

    tree:
        system_configuration:
            commerce:
                children:
                    design:
                        priority: 800
                        children:
                            theme:
                                children:
                                    theme_settings:
                                        children:
                                            - oro_frontend.frontend_theme
                                    page_templates:
                                        children:
                                            - oro_frontend.page_templates
